version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: appointment-api
    container_name: appointment-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - appointment-network

  nginx:
    image: nginx:alpine
    container_name: appointment-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appointment-network

  db:
    image: mysql:8.0
    container_name: appointment-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: appointment_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: appointment_user
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - appointment-network

networks:
  appointment-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
